//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace DataDownloader.pubmed
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]

    public partial class eSearchResult
    {

        public int Count;

        public int RetMax;

        public int RetStart;

        public int QueryKey;

        public string WebEnv;

        [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable = false)]
        public int[] IdList;

        public object TranslationSet;

        public eSearchResultTranslationStack TranslationStack;

        public string QueryTranslation;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class eSearchResultTranslationStack
    {

        public eSearchResultTranslationStackTermSet TermSet;

        public string OP;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class eSearchResultTranslationStackTermSet
    {

        public string Term;

        public string Field;

        public int Count;

        public string Explode;
    }

    public partial class ePostResult
    {
        public int QueryKey;

        public string WebEnv;
    }

}